name: Keep Alive

on:
  schedule:
    - cron: "*/15 * * * *"  

jobs:
  ping-with-browser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Load Streamlit Apps
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({
              headless: 'new',
              args: ['--no-sandbox']
            });
            const page = await browser.newPage();

            // Primeiro app
            console.log('Acessando govinsights...');
            await page.goto('https://govinsights.streamlit.app/', { waitUntil: 'networkidle2' });
            await new Promise(r => setTimeout(r, 5000));

            // Espera entre os acessos
            console.log('Esperando 10s...');
            await new Promise(r => setTimeout(r, 10000));

            // Segundo app
            console.log('Acessando dashgovinsights...');
            await page.goto('https://dashgovinsights.streamlit.app/', { waitUntil: 'networkidle2' });
            await new Promise(r => setTimeout(r, 5000));

            await browser.close();
            console.log('Finalizado.');
          })();
          "
