# Nome do Workflow
name: Keep Streamlit App Alive

# Gatilho (trigger) do workflow
on:
  schedule:
    # Executa a cada 15 minutos. A sintaxe é de cron job.
    # '*/15' -> a cada 15 minutos
    # '*' -> toda hora, todo dia do mês, todo mês, todo dia da semana
    - cron: '*/15 * * * *'

jobs:
  # Nome do job
  wake-up:
    # O tipo de máquina virtual para executar o job
    runs-on: ubuntu-latest

    steps:
      # Use o 'curl' para enviar uma requisição HTTP para a URL da sua aplicação
      - name: Wake up govinsights.streamlit.app
        run: curl -A "Mozilla/5.0" -s "https://govinsights.streamlit.app/" || true

      - name: Wake up dashgovinsights.streamlit.app
        run: curl -A "Mozilla/5.0" -s "https://dashgovinsights.streamlit.app/" || true
